
GET http://localhost:3000/api/blogs

###

POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "Bob the Clown",
    "author": "Joe Biden",
    "url": "maxthedebt.com",
    "likes": 3
}