
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "secret"
}

###

GET http://localhost:3000/api/blogs

###

POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNTgyOGMyYzZmYzdjOGE3MTA5ZDc3ZSIsImlhdCI6MTY2NjczNTk0MH0.p6Arh9wxPzMX5wQXt2lHaAcj1OuHMn44wJ4RD5r8dlY

{
    "title": "Thiccness",
    "author": "Dummy",
    "url": "www.usa.gov",
    "likes": 3
}

###

DELETE http://localhost:3000/api/blogs/635860e3182f7378da88ee92
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNTgyOGMyYzZmYzdjOGE3MTA5ZDc3ZSIsImlhdCI6MTY2NjczNTk0MH0.p6Arh9wxPzMX5wQXt2lHaAcj1OuHMn44wJ4RD5r8dlY


###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "secret"
}