
GET http://localhost:3000/api/blogs

###

POST http://localhost:3000/api/blogs
Content-Type: application/json

{
    "title": "Bob the Clown",
    "author": "Mr. Clown",
    "url": "maxthedebt.com",
    "likes": 3
}

###

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "root",
    "password": "secret"
}